{
	"result": [
		{
			"email": "agata.wawrzynczak@amu.edu.pl",
			"Registration_Status__c": "valid",
			"firstName": "Agata",
			"lastName": "Wawrzyńczak",
			"company": "Adam Mickiewicz University in Poznań, Faculty of Chemistry",
			"country": "Poland",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "105784797",
			"addToList": "93319"
		},
		{
			"email": "akocaysel@yahoo.com",
			"Registration_Status__c": "valid",
			"firstName": "aysel",
			"lastName": "Demir",
			"company": "Ankara University",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107343537",
			"addToList": "93319"
		},
		{
			"email": "akram.keramat@bio.uni-stuttgart.de",
			"Registration_Status__c": "valid",
			"firstName": "Akram",
			"lastName": "Keramat",
			"company": "Stuttgart Universität ",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106801052",
			"addToList": "93319"
		},
		{
			"email": "andres@luxembourg.co.il",
			"Registration_Status__c": "valid",
			"firstName": "Andres",
			"lastName": "Novoa",
			"company": "Luxembourg Ind., Ltd.",
			"country": "Israel",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "103889055",
			"addToList": "93319"
		},
		{
			"email": "andrew_zumbusch@cargill.com",
			"Registration_Status__c": "valid",
			"firstName": "Andrew",
			"lastName": "Zumbusch",
			"company": "Cargill",
			"country": "United States",
			"state": "Minnesota",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "83919439",
			"addToList": "93319"
		},
		{
			"email": "aradc059@uottawa.ca",
			"Registration_Status__c": "valid",
			"firstName": "Aliaksandra",
			"lastName": "Radchanka",
			"company": "University of Ottawa",
			"country": "Canada",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107155177",
			"addToList": "93319"
		},
		{
			"email": "asma.kasmani@crl.com",
			"Registration_Status__c": "valid",
			"firstName": "Asma",
			"lastName": "Kasmani",
			"company": "Charles River Labs",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107118694",
			"addToList": "93319"
		},
		{
			"email": "blee28@its.jnj.com",
			"Registration_Status__c": "valid",
			"firstName": "Beeah",
			"lastName": "Lee",
			"company": "Johnsons & Johnson",
			"country": "United States",
			"state": "Pennsylvania",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "88411397",
			"addToList": "93319"
		},
		{
			"email": "carmen_gaidau@hotmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Carmen",
			"lastName": "Gaidau",
			"company": "R & D National Institute for Textiles & Leather",
			"country": "Romania",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "101379945",
			"addToList": "93319"
		},
		{
			"email": "caroline.parneix@loreal.com",
			"Registration_Status__c": "valid",
			"firstName": "Caroline",
			"lastName": "Parneix",
			"company": "L'Oréal",
			"country": "France",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "102215660",
			"addToList": "93319"
		},
		{
			"email": "chertopalov@fzu.cz",
			"Registration_Status__c": "valid",
			"firstName": "Sergii",
			"lastName": "Chertopalov",
			"company": "the Institute of Physics of CAS",
			"country": "Czech Republic",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "98507545",
			"addToList": "93319"
		},
		{
			"email": "choriegomarin.1@buckeyemail.osu.edu",
			"Registration_Status__c": "valid",
			"firstName": "Rolando",
			"lastName": "Choriego",
			"company": "The Ohio State University",
			"country": "United States",
			"state": "Ohio",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107351349",
			"addToList": "93319"
		},
		{
			"email": "claire.patterson@sedapds.com",
			"Registration_Status__c": "valid",
			"firstName": "Claire",
			"lastName": "Patterson",
			"company": "Seda Pharmaceutical Development Services",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "82100155",
			"addToList": "93319"
		},
		{
			"email": "danaculita@yahoo.co.uk",
			"Registration_Status__c": "valid",
			"firstName": "Daniela",
			"lastName": "Culita",
			"company": "Ilie Murgulescu Institute of Physical Chemistry",
			"country": "Romania",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107123923",
			"addToList": "93319"
		},
		{
			"email": "daniel.truchan@savba.sk",
			"Registration_Status__c": "valid",
			"firstName": "Daniel",
			"lastName": "Truchan",
			"company": "Institute of Physics, Slovak Academy of Sciences",
			"country": "Slovakia",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107343996",
			"addToList": "93319"
		},
		{
			"email": "debprasad.neuro@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Debprasad",
			"lastName": "Dutta",
			"company": "Mazumdar Shaw Medical Foundation (MSMF)",
			"country": "India",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107349399",
			"addToList": "93319"
		},
		{
			"email": "div.chauhan87@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Divyesh",
			"lastName": "Chauhan",
			"company": "Sun Pharmaceutical Industries Ltd",
			"country": "India",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "94776522",
			"addToList": "93319"
		},
		{
			"email": "dmetzler@its.jnj.com",
			"Registration_Status__c": "valid",
			"firstName": "David",
			"lastName": "Metzler",
			"company": "Johnson & Johnson Innovative Medicine",
			"country": "United States",
			"state": "PA",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "96523465",
			"addToList": "93319"
		},
		{
			"email": "enesfurkansakar18@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Enes Furkan",
			"lastName": "SAKAR",
			"company": "TUBITAK",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "102050840",
			"addToList": "93319"
		},
		{
			"email": "esarioglu21@ku.edu.tr",
			"Registration_Status__c": "valid",
			"firstName": "Ebru",
			"lastName": "Sarıoğlu",
			"company": "Koç University",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "95526140",
			"addToList": "93319"
		},
		{
			"email": "etekle@hikma.com",
			"Registration_Status__c": "valid",
			"firstName": "Esayas",
			"lastName": "Tekle",
			"company": "Hikma Pharmaceuticals",
			"country": "United States",
			"state": "Ohio",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "100422181",
			"addToList": "93319"
		},
		{
			"email": "fabienne.praxmarer@losan.de",
			"Registration_Status__c": "valid",
			"firstName": "Fabienne",
			"lastName": "Praxmarer",
			"company": "Losan Pharma GmbH",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "94337229",
			"addToList": "93319"
		},
		{
			"email": "federica.zuppardi@ipcb.cnr.it",
			"Registration_Status__c": "valid",
			"firstName": "FEDERICA",
			"lastName": "zuppardi",
			"company": "CNR",
			"country": "Italy",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "95962912",
			"addToList": "93319"
		},
		{
			"email": "fouzia.machrouhi-porcher@merckgroup.com",
			"Registration_Status__c": "valid",
			"firstName": "Fouzia",
			"lastName": "Machrouhi",
			"company": "Merck",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106825967",
			"addToList": "93319"
		},
		{
			"email": "g_yuksel@ogr.eskisehir.edu.tr",
			"Registration_Status__c": "valid",
			"firstName": "Gamze",
			"lastName": "YÜKSEL",
			"company": "Eskişehir Technical University",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107346912",
			"addToList": "93319"
		},
		{
			"email": "georgina.x.armstrong@gsk.com",
			"Registration_Status__c": "valid",
			"firstName": "Georgina",
			"lastName": "Armstrong",
			"company": "GSK",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "94769212",
			"addToList": "93319"
		},
		{
			"email": "gorkemy182@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "gorkem onur",
			"lastName": "yildirim",
			"company": "eskisehir technical university",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "107352537",
			"addToList": "93319"
		},
		{
			"email": "guveng15@itu.edu.tr",
			"Registration_Status__c": "valid",
			"firstName": "Gülşah",
			"lastName": "Güven",
			"company": "İstanbul Technical University",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107348382",
			"addToList": "93319"
		},
		{
			"email": "hank.khavo@seqirus.com",
			"Registration_Status__c": "valid",
			"firstName": "Hank",
			"lastName": "Khavo",
			"company": "Seqirus",
			"country": "United States",
			"state": "NC",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "45653758",
			"addToList": "93319"
		},
		{
			"email": "hannah.buckland@malvernpanalytical.com",
			"Registration_Status__c": "valid",
			"firstName": "Hannah",
			"lastName": "Buckland",
			"company": "Malvern Panalytical",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "104159769",
			"addToList": "93319"
		},
		{
			"email": "haraya@nihs.go.jp",
			"Registration_Status__c": "valid",
			"firstName": "Yuki",
			"lastName": "Haraya",
			"company": "National Institute of Health Sciences",
			"country": "Japan",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107149224",
			"addToList": "93319"
		},
		{
			"email": "heather.mcauliffe@cormica.com",
			"Registration_Status__c": "valid",
			"firstName": "Heather",
			"lastName": "McAuliffe",
			"company": "Cormica",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104913951",
			"addToList": "93319"
		},
		{
			"email": "heeralal.bassi@biontech.de",
			"Registration_Status__c": "valid",
			"firstName": "Heeralal",
			"lastName": "Bassi",
			"company": "Biontech Se",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "97479160",
			"addToList": "93319"
		},
		{
			"email": "huey.lee@siemens-healthineers.com",
			"Registration_Status__c": "valid",
			"firstName": "Huey",
			"lastName": "Lee",
			"company": "Siemens Healthineers",
			"country": "United States",
			"state": "New York",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "83603444",
			"addToList": "93319"
		},
		{
			"email": "ingela.carlen@malvernpanalytical.com",
			"Registration_Status__c": "valid",
			"firstName": "Ingela ",
			"lastName": "Carlen ",
			"company": "MP",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "98646460",
			"addToList": "93319"
		},
		{
			"email": "katy.dickinson@cormica.com",
			"Registration_Status__c": "valid",
			"firstName": "Katy",
			"lastName": "Dickinson",
			"company": "Cormica Bradford",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "105784416",
			"addToList": "93319"
		},
		{
			"email": "lamtuongvi.tran@uqconnect.edu.au",
			"Registration_Status__c": "valid",
			"firstName": "Lam Tuong Vi",
			"lastName": "Tran",
			"company": "University of Queensland",
			"country": "Australia",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106975483",
			"addToList": "93319"
		},
		{
			"email": "lee_byung_kook@lilly.com",
			"Registration_Status__c": "valid",
			"firstName": "qook",
			"lastName": "lee",
			"company": "Eli Lilly",
			"country": "United States",
			"state": "MA",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "34968132",
			"addToList": "93319"
		},
		{
			"email": "leonardu002@e.ntu.edu.sg",
			"Registration_Status__c": "valid",
			"firstName": "leonardus",
			"lastName": "depari",
			"company": "NTU",
			"country": "Singapore",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107236440",
			"addToList": "93319"
		},
		{
			"email": "marcosvinicius.delimatinoco-ext@syensqo.com",
			"Registration_Status__c": "valid",
			"firstName": "Marcos ",
			"lastName": "Tinoco",
			"company": "Syensqo",
			"country": "Brazil",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106854944",
			"addToList": "93319"
		},
		{
			"email": "mayuribirajdar388@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Mayuri",
			"lastName": "Birajdar",
			"company": "National institute of pharmaceutical educational and research, Raebareli ",
			"country": "India",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "103797413",
			"addToList": "93319"
		},
		{
			"email": "meltemipekci@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Meltem",
			"lastName": "İpekçi",
			"company": "İTÜ",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107356228",
			"addToList": "93319"
		},
		{
			"email": "meltemterzioglu@kale.com.tr",
			"Registration_Status__c": "valid",
			"firstName": "Meltem",
			"lastName": "Ipekci-Terzioglu",
			"company": "Kalekim",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "92359592",
			"addToList": "93319"
		},
		{
			"email": "mfrancacamila@usp.br",
			"Registration_Status__c": "valid",
			"firstName": "Camila",
			"lastName": "Almeida",
			"company": "USP",
			"country": "Brazil",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "96349424",
			"addToList": "93319"
		},
		{
			"email": "michael.ahlering@cordis.com",
			"Registration_Status__c": "valid",
			"firstName": "Michael",
			"lastName": "Ahlering",
			"company": "Cordis Corp.",
			"country": "United States",
			"state": "california",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "107346126",
			"addToList": "93319"
		},
		{
			"email": "michael.fallon@sgs.com",
			"Registration_Status__c": "valid",
			"firstName": "Michael",
			"lastName": "Fallon",
			"company": "SGS ISL Ltd.",
			"country": "Ireland",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "92699914",
			"addToList": "93319"
		},
		{
			"email": "monika.prasnikar@ffa.uni-lj.si",
			"Registration_Status__c": "valid",
			"firstName": "Monika",
			"lastName": "Prašnikar",
			"company": "University of Ljubljana, Faculty of Pharmacy",
			"country": "Slovenia",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "102309473",
			"addToList": "93319"
		},
		{
			"email": "morgan.delong@sri.com",
			"Registration_Status__c": "valid",
			"firstName": "Morgan",
			"lastName": "DeLong",
			"company": "SRI International",
			"country": "United States",
			"state": "Virginia",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "94941008",
			"addToList": "93319"
		},
		{
			"email": "muhammadayyaz333@yahoo.com",
			"Registration_Status__c": "valid",
			"firstName": "Muhammad",
			"lastName": "Ayyaz",
			"company": "Department of Materials Engineering, Politechnico di Milano",
			"country": "Italy",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107290137",
			"addToList": "93319"
		},
		{
			"email": "neil.forbes@vectura.com",
			"Registration_Status__c": "valid",
			"firstName": "Neil ",
			"lastName": "Forbes",
			"company": "Vectura",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "94471771",
			"addToList": "93319"
		},
		{
			"email": "nelli.laleni@malvernpanalytical.com",
			"Registration_Status__c": "valid",
			"firstName": "Nelli",
			"lastName": "Laleni",
			"company": "Malvern Panalytical",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "98369362",
			"addToList": "93319"
		},
		{
			"email": "nick.watterson@malvernpanalytical.com",
			"Registration_Status__c": "valid",
			"firstName": "nick",
			"lastName": "watterson",
			"company": "malvern panalytical",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104047827",
			"addToList": "93319"
		},
		{
			"email": "nicole.mackala@curevac.com",
			"Registration_Status__c": "valid",
			"firstName": "Nicole",
			"lastName": "Mackala",
			"company": "CureVac SE",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "98148732",
			"addToList": "93319"
		},
		{
			"email": "nikola.ilic@vin.bg.ac.rs",
			"Registration_Status__c": "valid",
			"firstName": "Nikola",
			"lastName": "Ilic",
			"company": "Vinca Institute of Nuclear Sciences",
			"country": "Serbia",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107224446",
			"addToList": "93319"
		},
		{
			"email": "nshukla8@its.jnj.com",
			"Registration_Status__c": "valid",
			"firstName": "Neetu",
			"lastName": "Shukla",
			"company": "Johnson & Johnson",
			"country": "United States",
			"state": "PA",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106033555",
			"addToList": "93319"
		},
		{
			"email": "nt484@cam.ac.uk",
			"Registration_Status__c": "valid",
			"firstName": "Nathalie",
			"lastName": "Tarabay",
			"company": "University of Cambridge",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "107354293",
			"addToList": "93319"
		},
		{
			"email": "oguz.yucel@iuc.edu.tr",
			"Registration_Status__c": "valid",
			"firstName": "Oguz",
			"lastName": "Yucel",
			"company": "Istanbul University-Cerrahpasa",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104326372",
			"addToList": "93319"
		},
		{
			"email": "olivia.ke@omec-instruments.com",
			"Registration_Status__c": "valid",
			"firstName": "Olivia",
			"lastName": "Ke",
			"company": "Zhuhai OMEC Instrruments Co., Ltd.",
			"country": "China",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "101603059",
			"addToList": "93319"
		},
		{
			"email": "onurzirhli@sabanciuniv.edu",
			"Registration_Status__c": "valid",
			"firstName": "Onur",
			"lastName": "ZIRHLI",
			"company": "Sabancı Üniversitesi",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107344878",
			"addToList": "93319"
		},
		{
			"email": "priya.gupta@malvernpanalytical.com",
			"Registration_Status__c": "valid",
			"firstName": "Priya",
			"lastName": "Gupta",
			"company": "MP",
			"country": "Afghanistan",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104274703",
			"addToList": "93319"
		},
		{
			"email": "ptrw@novonordisk.com",
			"Registration_Status__c": "valid",
			"firstName": "peter",
			"lastName": "witts",
			"company": "Novo Nordisk Production Ireland Limited",
			"country": "Ireland",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107130396",
			"addToList": "93319"
		},
		{
			"email": "qaisersaleem071@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Dr Qasar ",
			"lastName": "Saleem ",
			"company": "University of Management and Technology,Lahore ",
			"country": "Pakistan",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "103709756",
			"addToList": "93319"
		},
		{
			"email": "remijn.sandra@sysmex.nl",
			"Registration_Status__c": "valid",
			"firstName": "Sandra",
			"lastName": "Remijn",
			"company": "Sysmex",
			"country": "Netherlands",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "27346486",
			"addToList": "93319"
		},
		{
			"email": "sandeep@lansdowneengineering.com",
			"Registration_Status__c": "valid",
			"firstName": "sandeep",
			"lastName": "Nair",
			"company": "Lansdowne Engineering",
			"country": "Canada",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "86182263",
			"addToList": "93319"
		},
		{
			"email": "sattar.eghbalian@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Sattar",
			"lastName": "EGHBALIAN",
			"company": "University of Hacettepe",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "99790875",
			"addToList": "93319"
		},
		{
			"email": "seher.kucuk@ikc.edu.tr",
			"Registration_Status__c": "valid",
			"firstName": "Seher",
			"lastName": "Küçük",
			"company": "Univercity",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "107355739",
			"addToList": "93319"
		},
		{
			"email": "selin.daglar@sabanciuniv.edu",
			"Registration_Status__c": "valid",
			"firstName": "selin",
			"lastName": "dağlar",
			"company": "SUNUM",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107341965",
			"addToList": "93319"
		},
		{
			"email": "sevgican-91@hotmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Sevgi ",
			"lastName": "Tuncer",
			"company": "Organik Kimya",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107353912",
			"addToList": "93319"
		},
		{
			"email": "shanthi_ml@yahoo.co.in",
			"Registration_Status__c": "valid",
			"firstName": "michael",
			"lastName": "SL Shanthi",
			"company": "Bharathidasan University",
			"country": "India",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "26155614",
			"addToList": "93319"
		},
		{
			"email": "shaoqiu.zhuo@revance.com",
			"Registration_Status__c": "valid",
			"firstName": "Shaoqiu",
			"lastName": "Zhuo",
			"company": "Revance Therapeutics",
			"country": "United States",
			"state": "California",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104557492",
			"addToList": "93319"
		},
		{
			"email": "shielann.baruti@aeciworld.com",
			"Registration_Status__c": "valid",
			"firstName": "Boitumelo",
			"lastName": "Baruti",
			"company": "AECI Mining Chemicals",
			"country": "South Africa",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "97997959",
			"addToList": "93319"
		},
		{
			"email": "shuyu.xu@ashland.com",
			"Registration_Status__c": "valid",
			"firstName": "Shuyu",
			"lastName": "Xu",
			"company": "Ashland Specialty Ingredients",
			"country": "United States",
			"state": "Delaware",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "96313622",
			"addToList": "93319"
		},
		{
			"email": "spomenka.milak@curevac.com",
			"Registration_Status__c": "valid",
			"firstName": "Spomenka",
			"lastName": "Milak",
			"company": "CureVac",
			"country": "Germany",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "102334632",
			"addToList": "93319"
		},
		{
			"email": "sru@buhlmannlabs.ch",
			"Registration_Status__c": "valid",
			"firstName": "Serena",
			"lastName": "Rudy",
			"company": "Bühlmann Laboratories",
			"country": "Switzerland",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107117101",
			"addToList": "93319"
		},
		{
			"email": "suleymanova.samira1990@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Samira",
			"lastName": "Suleymanova",
			"company": "Institute of Catalysis and Inorganic Chemistry",
			"country": "Azerbaijan",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "88012345",
			"addToList": "93319"
		},
		{
			"email": "susanarodrigues@avaxzipen.com",
			"Registration_Status__c": "valid",
			"firstName": "Susana",
			"lastName": "Rodrigues",
			"company": "aVaxziPen",
			"country": "United Kingdom",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "106137634",
			"addToList": "93319"
		},
		{
			"email": "tamiris.figueiredo@debiopharm.com",
			"Registration_Status__c": "valid",
			"firstName": "Tamiris",
			"lastName": "Figueiredo",
			"company": "Debiopharm Research & Manufacturing",
			"country": "Switzerland",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "102906317",
			"addToList": "93319"
		},
		{
			"email": "thoa@fertin.com",
			"Registration_Status__c": "valid",
			"firstName": "Thomas",
			"lastName": "Andresen",
			"company": "Fertin Pharma",
			"country": "Denmark",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "98833810",
			"addToList": "93319"
		},
		{
			"email": "tup19054@temple.edu",
			"Registration_Status__c": "valid",
			"firstName": "TUTUN DAS",
			"lastName": "AKA",
			"company": "Temple University",
			"country": "United States",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "104878875",
			"addToList": "93319"
		},
		{
			"email": "uc47642@uc.pt",
			"Registration_Status__c": "valid",
			"firstName": "Teresa",
			"lastName": "Costa",
			"company": "University of Coimbra",
			"country": "Portugal",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107217963",
			"addToList": "93319"
		},
		{
			"email": "vmserrano@inescop.es",
			"Registration_Status__c": "valid",
			"firstName": "VICTOR MANUEL",
			"lastName": "SERRANO MARTINEZ",
			"company": "INESCOP",
			"country": "Spain",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "104840280",
			"addToList": "93319"
		},
		{
			"email": "yldyorulmaz@sabanciuniv.edu",
			"Registration_Status__c": "valid",
			"firstName": "Yelda",
			"lastName": "Yorulmaz",
			"company": "Sabanci University",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "92288996",
			"addToList": "93319"
		},
		{
			"email": "yuqing.zhu@henkel.com",
			"Registration_Status__c": "valid",
			"firstName": "Jane",
			"lastName": "Zhu",
			"company": "Henkel",
			"country": "United States",
			"state": "NJ",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "102424878",
			"addToList": "93319"
		},
		{
			"email": "zehra.cobandede@sabanciuniv.edu",
			"Registration_Status__c": "valid",
			"firstName": "Zehra",
			"lastName": "Çobandede",
			"company": "Sabanci University Nanotechnolgy Research and Application Center",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107341578",
			"addToList": "93319"
		},
		{
			"email": "zsuzsanna.foldvari@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Zsuzsanna",
			"lastName": "Foldvari",
			"company": "AECI Mining Chemicals",
			"country": "South Africa",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "true",
			"campaignId": "1623",
			"matchId": "107354272",
			"addToList": "93319"
		},
		{
			"email": "zynep.dgn2434@gmail.com",
			"Registration_Status__c": "valid",
			"firstName": "Zeynep",
			"lastName": "Doğan",
			"company": "Eskisehir Technical University ",
			"country": "Turkey",
			"state": "",
			"Webinar_Opt_In__c": "",
			"Webinar_ID__c": "Masterclass 4: Data interpretation for Zeta potential",
			"Webinar_attended__c": "false",
			"campaignId": "1623",
			"matchId": "107352540",
			"addToList": "93319"
		}
	]
}